# Generated by Django 5.0.6 on 2025-11-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_app', '0002_contactmessage_first_name_contactmessage_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='newsletter_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
