# Generated by Django 5.0.6 on 2025-11-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_app', '0003_contactmessage_newsletter_opt_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='satisfaction',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Négatif'), (1, 'Neutre'), (2, 'Positif')], default=1, help_text='0 = négatif, 1 = neutre, 2 = positif'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='satisfaction_score',
            field=models.FloatField(default=1.0, help_text='Score pondéré du classifieur (0..2).'),
        ),
    ]
