# Generated by Django 5.0.6 on 2026-01-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_app', '0004_alter_contactmessage_satisfaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='satisfaction',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Negatif'), (1, 'Positif')], default=0, help_text='0 = negatif, 1 = positif'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='satisfaction_score',
            field=models.FloatField(default=0.5, help_text="Probabilite estimee d'etre positif (0..1)."),
        ),
    ]
