# Generated by Django 5.0.6 on 2026-01-06 18:18

from django.db import migrations, models


def convert_satisfaction_boolean_to_smallint(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT data_type
            FROM information_schema.columns
            WHERE table_name = 'weeb_app_contactmessage'
              AND column_name = 'satisfaction';
            """
        )
        row = cursor.fetchone()
    if not row or row[0] != "boolean":
        return
    schema_editor.execute(
        """
        ALTER TABLE weeb_app_contactmessage
        ALTER COLUMN satisfaction
        TYPE smallint
        USING CASE
            WHEN satisfaction IS TRUE THEN 1
            WHEN satisfaction IS FALSE THEN 0
            ELSE 0
        END;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_app', '0004_alter_contactmessage_satisfaction_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_satisfaction_boolean_to_smallint, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contactmessage',
            name='satisfaction',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Negatif'), (1, 'Positif')], default=0, help_text='0 = negatif, 1 = positif'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='satisfaction_score',
            field=models.FloatField(default=0.5, help_text="Probabilite estimee d'etre positif (0..1)."),
        ),
    ]
