[pytest]
DJANGO_SETTINGS_MODULE = weeb_backend.settings.development
pythonpath = weeb_backend
testpaths = weeb_backend
addopts = --cov=weeb_backend --cov-report=term-missing --cov-report=html --cov-config=.coveragerc
